### ISSUE TITLE
java.lang.ClassCastException in PlayerActivity.onCreate

### ISSUE THREAD

**Issue by luigitus** [StrimBagZ/StrimBagZ#6]
Device: Nexus 7 (2012)
OS: Android 4.4

Stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.lubot.strimbagz/net.lubot.strimbagz.util.PlayerActivity}: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.widget.LinearLayout
	at net.lubot.strimbagz.util.PlayerActivity.onCreate(PlayerActivity.java:244)
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
	... 11 more

Cause of the problem: Loading the wrong layout, looking into that problem right now

**Comment by luigitus** [comment]
This problem occurs on 7 inch tablets that are on portrait orientation, because the layouts.xml in /res/values-large contains isTablet true, it tries to initialize the tablet layout, but there is only a tablet layout for large on landscape orientation (/res/layout-large-land), because of that Android fallsback to /res/layout which causes the app to crash on 7 inch tablets

**Comment by luigitus** [comment]
Fixed.
